# Generated by Django 4.1 on 2022-09-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_alter_songfile_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='difficulty_level',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
