# Generated by Django 4.1.1 on 2023-01-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_alter_song_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='release_date',
            field=models.IntegerField(default=0),
        ),
    ]
