# Generated by Django 4.1.1 on 2023-01-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_song_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
