# Generated by Django 4.1.1 on 2023-01-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_song_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='difficulty_level',
            field=models.FloatField(),
        ),
    ]
