# Generated by Django 4.1.1 on 2023-07-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_song_album_song_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='description_file',
            field=models.FileField(null=True, upload_to='description_files'),
        ),
        migrations.AddField(
            model_name='songfile',
            name='score_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
