# Generated by Django 4.1.1 on 2023-08-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0007_song_description_file_songfile_score_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='visibility',
            field=models.IntegerField(default=1),
        ),
    ]
