# Generated by Django 4.2.7 on 2024-03-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0008_song_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='songfile',
            name='file_type',
            field=models.CharField(default='musicxml', max_length=50),
        ),
    ]
